site_name: Warwick's OCaml notes
repo_url: https://github.com/wrmack/mkdocs-gh-ocaml
nav:
  - Introduction:
    - Introduction: index.md
  - Getting started:
    - Install OCaml: 'Getting started/installation.md'
    - opam: 'Getting started/opam.md'
    - utop: 'Getting started/utop.md'
    - OCaml manual notation: 'Getting started/manual.md'
    - Style guide: 'Getting started/styleguide.md'
  - Understanding:
    - Do I need this?: 'Understanding/overview.md'
    - Functional programming: 'Understanding/functional.md'
    - Lambda calculus: 'Understanding/lambda.md'
    - Mutability: 'Understanding/mutability.md'
    - Types, maths and logic: 'Understanding/logic.md'
  - Type system: 
    - Understanding types: 'Type system/understand.md'
    - Predefined types: 'Type system/builtin.md'
    - User-defined types: 'Type system/user.md'
    - Parameterised types: 'Type system/parameterised.md'
    - Polymorphic variants: 'Type system/polymorphic.md'
    - Generalized Algebraic Datatypes (GADT): 'Type system/gadt.md'
    - Reading signatures:
       - Why?: 'Type system/Signatures/introduction.md'
       - cmdliner: 'Type system/Signatures/cmdliner.md'
       - ocsigen: 'Type system/Signatures/ocsigen.md'
  - Basics:
    - let: 'let.md'
    - Operators: 'operators.md'
    - Functions: 
      - Functions: Functions/functions.md
      - Recursive functions: Functions/recursion.md
    - Primitives: primitives.md
    - Collections of primitives:
      - Lists: 
        - Create and access a list: Lists/list_create.md
        - Operations on lists: Lists/list_ops.md   
      - Arrays:
        - Create and access an array: Arrays/array_create.md
        - Operations on arrays: Arrays/array_ops.md
      - Tuples: tuples.md
    - User-defined types:
      - Records: records.md
    - Control structures:
      - Overview: Controls/overview.md
      - if...else: Controls/ifelse.md
      - loops: Controls/loops.md
      - sequences: Controls/sequences.md
    - Data structures:
      - Data/hash_tables.md
      - Data/sequences.md
    - Printing: 
      - Simple printing: Printing/print.md
      - Format module: Printing/format.md
      - When debugging code: Printing/debugging.md
    - Modules: 
      - Basic modules: Modules/modules.md
      - Functors: Modules/functor.md
      - Make: Modules/make.md
      - Applicative functors: Modules/applicative.md      
      - Monads: Modules/monads.md
  - Libraries:
    - The standard library: Libraries/stdlib.md
    - Jane Street: Libraries/janest.md
    - Lwt: Libraries/lwt.md
  - Compiling and building:
    - Compiling code: Running/compile.md
    - Build with dune: Running/dune.md
  - Computer internals:
    - Processes, threads, frames, stack, heap: Internals/stackheap.md
    - Concurrency: Internals/concurrency.md
  - Appendix: 
    - Glossary: Appendix/glossary.md
    - Syntax summary: Appendix/syntax.md
    - Inspecting code: Appendix/introspection.md
    - Finding stuff: Appendix/finding.md
    - Filename extensions: Appendix/extensions.md
theme:
  name: material
  palette: 
    
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  features:
    - content.code.copy
    # - navigation.expand
    - navigation.sections 
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      title: 'On this page'
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - footnotes
  - tables
plugins:
  # - to-pdf:
  #     download_link: header
  # - git-revision-date-localized:
  #     enable_creation_date: false
  #     fallback_to_build_date: true
  - document-dates:
      position: bottom
      show_author: false